server:
  port: 8800
  context-path: /foodTruck-app

spring:
  application:
    name: foodTruck-app
  profiles:
    active: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        max:-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
      

logging:
  path: /logs/foodTruck


localFile:
  path: path/to/Mobile_Food_Facility_Permit.csv



